version: "3.1"

services:
  api_rinha_backend_master: &instance_a
      container_name: api_instance_a
      image: mmortiz/rinha-de-backend-2024-q1-api_rinha_backend_master:latest
      ports:
        - '127.0.0.1:8000:8000'
      environment:
        INSTANCE_BIND: "127.0.0.1:8000"
        INSTANCE_WORKERS: "2"
        INSTANCE_NAME: "api_instance_a"
        FIREBIRD_DSN: "localhost:/firebird/data/master.fdb"
        FIREBIRD_USER: "foo"
        FIREBIRD_PASSWORD: "foo@123"
        FIREBIRD_DATABASE: "master.fdb"
      deploy:
        resources:
          limits:
            cpus: '0.25'
            memory: '150MB'
      depends_on:
        - firebird_db
      network_mode: "host"

  api_rinha_backend_slave:
    <<: *instance_a
    container_name: api_instance_b
    ports:
      - '127.0.0.1:8001:8001'
    environment:
      INSTANCE_BIND: "127.0.0.1:8001"
      INSTANCE_WORKERS: "2"
      INSTANCE_NAME: "api_instance_b"
      FIREBIRD_DSN: "localhost:/firebird/data/master.fdb"
      FIREBIRD_USER: "foo"
      FIREBIRD_PASSWORD: "foo@123"
      FIREBIRD_DATABASE: "master.fdb"

  firebird_db:
    container_name: firebird_db
    image: jacobalberty/firebird
    ports:
      - '127.0.0.1:3050:3050'
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: '100MB'
    environment:
      FIREBIRD_USER: "foo"
      FIREBIRD_PASSWORD: "foo@123"
      TZ: "America/Sao_Paulo"
      FIREBIRD_DATABASE: "master.fdb"
    network_mode: "host"

  nginx_server:
    container_name: nginx_server
    restart: always
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - target: 9999
        published: 9999
        protocol: tcp
        mode: host
    environment:
      - TZ=America/Sao_Paulo
      - DEBIAN_FRONTEND=noninteractive
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '100MB'
    network_mode: "host"
